SELECT * FROM EMPLOYEES ;--FOR UPDATE;




-- QUERY ONE 
SELECT MAX(E.SALARY) AS SECOND_SALARY
 FROM EMPLOYEES E WHERE E.SALARY  < (SELECT MAX(T.SALARY) FROM EMPLOYEES T );

 --- SECOND QUERY 

 
SELECT *  
 FROM EMPLOYEES E WHERE E.SALARY  NOT IN (SELECT MAX(T.SALARY) FROM EMPLOYEES T )
 ORDER BY SALARY DESC
 FETCH FIRST  ROW ONLY ;--FETCH FIRST ROW ONLY is used to limit the result to just 1 row.

 -- THRID QUERY 

SELECT SALARY ,'SECOND HEIGHT' AS HEIGHT,RN 
FROM (
    SELECT DISTINCT SALARY ,ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS RN
    FROM EMPLOYEES
) WHERE RN =2;

--4 QUERY 


SELECT E.SALARY
FROM EMPLOYEES E 

GROUP BY E.SALARY ORDER BY E.SALARY DESC
OFFSET 1 ROWS FETCH FIRST ROW ONLY;

---5 QUERY


SELECT *
FROM (
    SELECT EMPLOYEES.*,
    DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RN
    FROM EMPLOYEES
) WHERE RN =2;

--6 QUERY 

SELECT MAX(SALARY) AS SECOND_HIGHEST 
FROM (SELECT DISTINCT SALARY,
      FIRST_VALUE(SALARY)
      OVER (ORDER BY SALARY DESC) AS TOTAL
      FROM EMPLOYEES)
    WHERE SALARY < TOTAL;